### ISSUE TITLE
Move files into ghw directory

### ISSUE THREAD

**Issue by retr0h** [jaypipes/ghw#42]
If we move the current files which implement the `ghw` package into `ghw/` directory, we can then move the `ghwc/main.go` to top level main and no longer require the ghwc directory.  #41 partially implements this, by moving vendor to top level.

**Comment by jaypipes** [comment]
I am hesitant to move the CLI tool into the top level because ghw is intended as a library first and foremost. The ghwc tool is merely an example of the library's usage. I wanted to keep the dependencies for the library at a minimum (or none at all) and that's why I had the vendor directory inside the ghwc/ directory -- to keep the deps for the example tool separate from the library itself. Make sense?

**Comment by retr0h** [comment]
Yeah, makes sense.
